apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: sampleapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sampleapp1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
      labels:
        app: sampleapp1
    spec:
      containers:
        - name: sampleapp
          image: fernandonogueira/spring-prometheus-sample:0.3
          ports:
            - containerPort: 8080
